##### Recomendar filme com base do quão é parecido (director, genre, writer, production_company, description)

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [2]:
df_movie_ratings = pd.read_csv('Arquivos/MovieRatingsTrated.csv', parse_dates=['date_published'])
df_movie_ratings.drop(columns=['imdb_title_id'], inplace=True)

---

### Verifico incosistências

In [3]:
df_movie_ratings['sum'] = df_movie_ratings.iloc[:, 19:].sum(axis=1).astype('int64')

In [4]:
for i in range(0, len(df_movie_ratings)):
    if df_movie_ratings['sum'][i] != len(df_movie_ratings['genre'][i].split(',')):
        print(i)

In [5]:
df_movie_ratings.drop(columns=['sum'], inplace=True)

---

In [6]:
df_movie_ratings.head(50)

,original_title,year,date_published,genre,duration,country,director,writer,production_company,actors,description,avg_vote,votes,weighted_average_vote,allgenders_18age_avg_vote,allgenders_30age_avg_vote,allgenders_45age_avg_vote,males_allages_avg_vote,females_allages_avg_vote,Romance,Drama,Western,Comedy,Horror,Adventure,Mystery,Sci-Fi,Thriller,Crime,Musical,Fantasy,Biography,Action,War,Family,History,Music,Animation,Sport,Film-Noir,Documentary,Reality-TV,News
0,Miss Jerry,1894,1894-10-09,Romance,45,USA,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,5.9,6.0,5.7,6.6,6.2,6.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,The Story of the Kelly Gang,1906,1906-12-26,"Biography,Crime,Drama",70,Australia,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,6.1,6.1,6.0,6.3,6.1,6.2,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.8,188,5.8,5.5,5.8,6.2,5.9,5.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Cleopatra,1912,1912-11-13,"Drama,History",100,USA,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,5.2,5.3,5.0,5.3,5.1,5.9,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
4,L'Inferno,1911,1911-03-06,"Adventure,Drama,Fantasy",68,Italy,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,7.0,7.0,7.0,7.1,7.0,7.2,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
5,"From the Manger to the Cross; or, Jesus of Naz...",1912,1913-01-01,"Biography,Drama",60,USA,Sidney Olcott,Gene Gauntier,Kalem Company,"R. Henderson Bland, Percy Dyer, Gene Gauntier,...","An account of the life of Jesus Christ, based ...",5.7,484,5.7,5.6,5.6,5.8,5.7,5.8,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
6,Madame DuBarry,1919,1919-11-26,"Biography,Drama,Romance",85,Germany,Ernst Lubitsch,"Norbert Falk, Hanns Kräly",Projektions-AG Union (PAGU),"Pola Negri, Emil Jannings, Harry Liedtke, Edua...","The story of Madame DuBarry, the mistress of L...",6.8,753,6.8,6.4,6.7,7.0,6.6,7.4,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
7,Quo Vadis?,1913,1913-03-01,"Drama,History",120,Italy,Enrico Guazzoni,"Henryk Sienkiewicz, Enrico Guazzoni",Società Italiana Cines,"Amleto Novelli, Gustavo Serena, Carlo Cattaneo...","An epic Italian film ""Quo Vadis"" influenced ma...",6.2,273,6.2,5.9,6.2,6.3,6.2,6.3,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
8,Independenta Romaniei,1912,1912-09-01,"History,War",120,Romania,"Aristide Demetriade, Grigore Brezeanu","Aristide Demetriade, Petre Liciu",Societatea Filmului de Arta Leon Popescu,"Aristide Demetriade, Constanta Demetriade, Con...",The movie depicts the Romanian War of Independ...,6.7,198,6.7,7.4,6.7,6.5,6.7,7.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
9,Richard III,1912,1912-10-15,Drama,55,"France, USA","André Calmettes, James Keane","James Keane, William Shakespeare",Le Film d'Art,"Robert Gemp, Frederick Warde, Albert Gardner, ...",Richard of Gloucester uses manipulation and mu...,5.5,225,5.5,5.9,5.3,5.8,5.5,7.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,Atlantis,1913,1913-12-26,Drama,121,Denmark,August Blom,"Axel Garde, Gerhart Hauptmann",Nordisk Film,"Olaf Fønss, Ida Orloff, Ebba Thomsen, Carl Lau...",After Dr. Friedrich's wife becomes mentally un...,6.6,331,6.6,6.3,6.6,6.8,6.5,7.1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,Fantômas - À l'ombre de la guillotine,1913,1913-05-12,"Crime,Drama",54,France,Louis Feuillade,"Marcel Allain, Louis Feuillade",Société des Etablissements L. Gaumont,"René Navarre, Edmund Breon, Georges Melchior, ...",Inspector Juve is tasked to investigate and ca...,7.0,1944,7.0,6.9,6.9,7.1,6.9,7.4,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,Ingeborg Holm,1913,1915-10-18,Drama,96,Sweden,Victor Sjöström,Nils Krok,Svenska Biografteatern AB,"Hilda Borgström, Aron Lindgren, Erik Lindholm,...",Single mother is separated from her children d...,7.1,948,7.1,7.0,6.9,7.3,7.0,7.4,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,Juve contre Fantômas,1913,1913-09-08,"Crime,Drama",61,France,Louis Feuillade,"Marcel Allain, Louis Feuillade",Société des Etablissements L. Gaumont,"René Navarre, Edmund Breon, Georges Melchior, ...",In Part Two of Louis Feuillade's 5 1/2-hour ep...,7.0,1349,7.0,6.8,6.9,7.1,6.9,7.2,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,Ma l'amor mio non muore...,1914,1914-01-01,Drama,90,Italy,Mario Caserini,"Emiliano Bonetti, G. Monleone",Film Artistica Gloria,"Lyda Borelli, Mario Bonnard, Gian Paolo Rosmin...","Leslie Swayne, an adventurer, in order to obta...",6.2,100,6.2,5.7,6.1,6.6,6.1,6.3,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,Maudite soit la guerre,1914,1914-05-01,"Drama,War",50,Belgium,Alfred Machin,Alfred Machin,Belge Cinéma Film,"Baert, Suzanne Berni, Fernand Crommelynck, Nad...",An army pilot is on a visit at the home of ano...,6.5,124,6.5,5.8,6.5,7.0,6.6,6.4,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
16,Le mort qui tue,1913,1913-11-06,"Crime,Drama,Mystery",90,France,Louis Feuillade,"Marcel Allain, Louis Feuillade",Société des Etablissements L. Gaumont,"René Navarre, Edmund Breon, Georges Melchior, ...",After a body disappears from inside the prison...,7.0,1050,7.0,6.8,6.9,7.1,6.9,7.5,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,"Home, Sweet Home",1914,1914-05-17,Drama,55,USA,D.W. Griffith,"D.W. Griffith, H.E. Aitken",Majestic Motion Picture Company,"Henry B. Walthall, Josephine Crowell, Lillian ...",John Howard Payne at his most miserable point ...,5.8,187,5.8,5.5,5.6,5.8,5.7,6.4,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,Der Student von Prag,1913,1913-08-22,"Drama,Fantasy,Horror",85,Germany,"Paul Wegener, Stellan Rye","Hanns Heinz Ewers, Hanns Heinz Ewers",Deutsche Bioscop GmbH,"Paul Wegener, Grete Berger, Lyda Salmonova, Jo...","Balduin, a student of Prague, leaves his royst...",6.5,1768,6.5,6.5,6.5,6.5,6.5,6.7,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
19,Gli ultimi giorni di Pompei,1913,1913-08-24,"Adventure,Drama",88,Italy,"Mario Caserini, Eleuterio Rodolfi","Edward George Bulwer-Lytton, Mario Caserini",Società Anonima Ambrosio,"Fernanda Negri Pouget, Eugenia Tettoni Fior, U...",Two love triangles intersect in ancient Pompei.,6.2,474,6.2,6.0,5.9,6.5,6.1,6.2,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20,Assunta Spina,1915,1916-05-01,Drama,72,Italy,"Francesca Bertini, Gustavo Serena","Salvatore Di Giacomo, Francesca Bertini",Caesar Film,"Francesca Bertini, Gustavo Serena, Carlo Benet...",Assunta Spina is a tragedy set in Naples at th...,6.4,378,6.4,6.2,6.2,6.7,6.4,6.9,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,The Avenging Conscience: or 'Thou Shalt Not Kill',1914,1914-08-24,"Crime,Drama,Horror",78,USA,D.W. Griffith,"Edgar Allan Poe, D.W. Griffith",Majestic Motion Picture Company,"Henry B. Walthall, Spottiswoode Aitken, Blanch...",Prevented from dating his sweetheart by his un...,6.4,1105,6.4,6.4,6.4,6.5,6.4,6.9,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,The Bargain,1914,1914-12-03,Western,70,USA,Reginald Barker,"William H. Clifford, Thomas H. Ince",New York Motion Picture,"William S. Hart, J. Frank Burke, Clara William...",After the bandit Jim Stokes robs the stage he ...,6.5,144,6.5,6.4,5.9,6.8,6.6,6.6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,Cabiria,1914,1914-04-18,"Adventure,Drama,History",148,Italy,Giovanni Pastrone,"Gabriele D'Annunzio, Titus Livius",Itala Film,"Carolina Catena, Lidia Quaranta, Gina Marangon...",Cabiria is a Roman child when her home is dest...,7.1,3073,7.1,7.0,7.0,7.2,7.1,6.9,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
24,Cinderella,1914,1914-12-28,"Fantasy,Drama",52,USA,James Kirkwood,Charles Perrault,Famous Players Film Company,"Mary Pickford, Owen Moore, Isabel Vernon, Geor...",Though mistreated by her cruel stepmother and ...,6.0,929,6.0,5.8,6.0,6.1,6.0,6.4,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
25,L'enfant de Paris,1913,1913-09-17,"Crime,Drama",124,France,Léonce Perret,Léonce Perret,Société des Etablissements L. Gaumont,"Léonce Perret, Louis Leubas, Maurice Lagrenée,...",The young daughter of an army captain missing ...,7.5,303,7.5,7.0,7.4,7.7,7.5,7.8,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26,Fantômas contre Fantômas,1914,1914-01-10,"Crime,Drama",59,France,Louis Feuillade,"Marcel Allain, Louis Feuillade",Société des Etablissements L. Gaumont,"René Navarre, Georges Melchior, Laurent Morléa...",The mystery of the drama is the appearance of ...,6.9,1161,6.9,6.7,6.9,6.9,6.8,7.4,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,A Florida Enchantment,1914,1916-09-04,Comedy,63,USA,Sidney Drew,"Marguerite Bertsch, Archibald Clavering Gunter",Vitagraph Company of America,"Sidney Drew, Edith Storey, Charles Kent, Mrs. ...",A young woman discovers a seed that can make w...,5.8,202,5.8,5.7,5.5,6.2,5.7,6.4,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28,Der Golem,1915,1915-04-08,Horror,60,Germany,"Henrik Galeen, Paul Wegener","Henrik Galeen, Paul Wegener",Deutsche Bioscop GmbH,"Paul Wegener, Henrik Galeen, Lyda Salmonova, R...","In this version of the golem legend, the golem...",6.8,1040,6.8,6.5,6.7,7.1,6.8,7.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,Det hemmelighedsfulde X,1914,1914-03-23,"Drama,Mystery",84,Denmark,Benjamin Christensen,"Benjamin Christensen, Laurids Skands",Dansk Biograf Compagni,"Benjamin Christensen, Karen Caspersen, Otto Re...","On the brink of war, Lt. van Hauen is summoned...",7.0,503,7.0,6.5,6.9,7.2,6.9,7.1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
30,"His Majesty, the Scarecrow of Oz",1914,1914-10-14,"Family,Fantasy,Adventure",59,USA,J. Farrell MacDonald,"L. Frank Baum, L. Frank Baum",The Oz Film Manufacturing Company,"Violet MacMillan, Frank Moore, Pierre Couderc,...","A wicked king has taken over the Emerald City,...",5.2,415,5.2,4.7,5.2,5.4,5.3,4.2,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0
31,Hypocrites,1915,1915-01-20,Drama,54,USA,Lois Weber,Lois Weber,Hobart Bosworth Productions,"Courtenay Foote, Myrtle Stedman, Herbert Stand...",The parallel stories of a modern preacher and ...,6.6,456,6.6,6.5,6.4,6.8,6.5,7.2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
32,In the Land of the Head Hunters,1914,1914-12-07,"Drama,History",65,"USA, Canada",Edward S. Curtis,Edward S. Curtis,Seattle Film Co.,"Stanley Hunt, Sarah Constance Smith Hunt, Mrs....","In 1911, as part of his massive undertaking, f...",5.8,402,5.8,5.7,5.7,6.1,5.8,6.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
33,Judith of Bethulia,1914,1914-03-08,Drama,61,USA,D.W. Griffith,"Thomas Bailey Aldrich, D.W. Griffith",Biograph Company,"Blanche Sweet, Henry B. Walthall, Mae Marsh, R...",A religious woman seeks to save her people fro...,6.1,1239,6.1,6.4,6.2,5.8,6.1,6.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
34,The Patchwork Girl of Oz,1914,1914-09-28,"Adventure,Family,Fantasy",81,USA,J. Farrell MacDonald,"L. Frank Baum, L. Frank Baum",The Oz Film Manufacturing Company,"Violet MacMillan, Frank Moore, Raymond Russell...","Ojo and Unc Nunkie are out of food, so they de...",5.5,382,5.5,4.7,5.3,6.0,5.5,5.5,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0
35,The Perils of Pauline,1914,1914-03-23,"Action,Adventure,Drama",199,USA,"Louis J. Gasnier, Donald MacKenzie","Charles W. Goddard, Basil Dickey",Pathé Frères,"Pearl White, Crane Wilbur, Paul Panzer, Edward...",Young Pauline is left a lot of money when her ...,6.3,939,6.3,5.6,6.4,6.4,6.2,6.8,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
36,The Squaw Man,1914,1914-02-15,"Action,Drama,Romance",74,USA,"Oscar Apfel, Cecil B. DeMille","Edwin Milton Royle, Cecil B. DeMille",Jesse L. Lasky Feature Play Company,"Dustin Farnum, Monroe Salisbury, Winifred King...",A chivalrous British officer takes the blame f...,5.7,879,5.7,5.5,5.5,6.0,5.7,5.9,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
37,Tess of the Storm Country,1914,1914-03-30,Drama,80,USA,Edwin S. Porter,"Grace Miller White, B.P. Schulberg",Famous Players Film Company,"Mary Pickford, Harold Lockwood, Olive Carey, D...",A wealthy resident attempts to dispossess squa...,6.1,178,6.1,5.5,5.8,6.6,6.1,6.5,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
38,A tolonc,1915,1915-03-20,Drama,67,Hungary,Michael Curtiz,"Jenö Janovics, Ede Tóth",ProJa Filmgyár,"Lili Berky, Victor Varconi, Mari Jászai, Andor...","Betty (Lili Berky, Duel For Nothing), a young ...",6.3,165,6.3,6.6,6.4,6.2,6.3,6.9,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
39,Uncle Tom's Cabin,1914,1914-08-10,Drama,54,USA,William Robert Daly,"Harriet Beecher Stowe, George L. Aiken",World Film,"Sam Lucas, Walter Hitchcock, Hattie Delaro, Ma...",A black and white silent film based on Harriet...,5.3,112,5.3,3.8,5.5,5.5,5.4,5.4,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
40,The Virginian,1914,1914-09-07,Western,55,USA,Cecil B. DeMille,"Owen Wister, Kirk La Shelle",Jesse L. Lasky Feature Play Company,"Dustin Farnum, Jack W. Johnston, Sydney Deane,...",A good-natured but chivalrous cowboy romances ...,5.6,174,5.6,6.0,5.2,5.7,5.5,5.9,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
41,The Wishing Ring: An Idyll of Old England,1914,1914-11-09,"Comedy,Drama",54,USA,Maurice Tourneur,"Owen Davis, Maurice Tourneur",Shubert Film Corporation,"Vivian Martin, Alec B. Francis, Chester Barnet...","After being expelled from college, Giles runs ...",6.4,242,6.4,5.9,6.3,6.7,6.5,6.1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42,The Wrath of the Gods,1914,1914-06-08,"Drama,Romance",56,USA,Reginald Barker,"William H. Clifford, Thomas H. Ince",New York Motion Picture,"Sessue Hayakawa, Tsuru Aoki, Frank Borzage, Ki...",An American sailor falls in love with a fisher...,5.7,138,5.7,5.5,5.5,6.0,5.6,5.9,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
43,Alias Jimmy Valentine,1915,1915-02-22,"Crime,Drama",65,USA,Maurice Tourneur,"Paul Armstrong, O. Henry",Peerless Productions,"Robert Warwick, Robert Cummings, Alec B. Franc...","After robbing a bank, a criminal is wrongfully...",6.6,206,6.6,6.2,6.5,6.9,6.6,7.0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44,Alice in Wonderland,1915,1915-01-19,"Adventure,Family,Fantasy",52,USA,W.W. Young,"Lewis Carroll, W.W. Young",Nonpareil Feature Film Corp.,"Viola Savoy, Herbert Rice, Harry Marks, Louis ...",Alice goes with her sister to a picnic and the...,6.2,394,6.2,6.4,5.9,6.5,6.1,6.7,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0
45,The Birth of a Nation,1915,1915-03-21,"Drama,History,War",195,USA,D.W. Griffith,"Thomas Dixon Jr., Thomas Dixon Jr.",David W. Griffith Corp.,"Henry B. Walthall, Lillian Gish, Mae Marsh, Mi...",The Stoneman family finds its friendship with ...,6.3,22213,6.3,6.0,6.3,6.7,6.4,5.7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
46,Carmen,1915,1915-10-31,Drama,59,USA,Cecil B. DeMille,"Prosper Mérimée, William C. de Mille",Jesse L. Lasky Feature Play Company,"Geraldine Farrar, Wallace Reid, Pedro de Cordo...","In order to help her smuggler kinsmen, a sultr...",6.4,894,6.4,6.3,6.4,6.3,6.4,6.4,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
47,The Cheat,1915,1915-12-13,"Drama,Romance",59,USA,Cecil B. DeMille,"Hector Turnbull, Jeanie Macpherson",Jesse L. Lasky Feature Play Company,"Fannie Ward, Sessue Hayakawa, Jack Dean, James...","A venal, spoiled stockbroker's wife impulsivel...",6.6,2305,6.6,6.3,6.4,7.0,6.6,6.9,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
48,The Coward,1915,1915-11-14,"Drama,History,War",77,USA,"Reginald Barker, Thomas H. Ince","Thomas H. Ince, Thomas H. Ince",Kay-Bee Pictures,"Frank Keenan, Charles Ray, Gertrude Claire, Pa...","Colonel Winslow, veteran of the Mexican War, h...",6.0,244,6.0,6.4,5.6,6.1,6.0,5.9,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
49,A Fool There Was,1915,1915-01-12,Drama,67,USA,Frank Powell,"Porter Emerson Browne, Roy L. McCardell",Fox Film Corporation,"Runa Hodges, Mabel Frenyear, Edward José, May ...",A married diplomat falls hopelessly under the ...,5.8,783,5.8,5.6,5.8,5.9,5.8,6.2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
df_movie_ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79379 entries, 0 to 79378
Data columns (total 43 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   original_title             79379 non-null  object
 1   year                       79379 non-null  int64
 2   date_published             79379 non-null  datetime64[ns]
 3   genre                      79379 non-null  object
 4   duration                   79379 non-null  int64
 5   country                    79379 non-null  object
 6   director                   79379 non-null  object
 7   writer                     79379 non-null  object
 8   production_company         79379 non-null  object
 9   actors                     79379 non-null  object
 10  description                79379 non-null  object
 11  avg_vote                   79379 non-null  float64
 12  votes                      79379 non-null  int64
 13  weighted_average_vote      79379 non-null  float64
 14  allgenders_18age_avg_vote  79379 non-null  float64
 15  allgenders_30age_avg_vote  79379 non-null  float64
 16  allgenders_45age_avg_vote  79379 non-null  float64
 17  males_allages_avg_vote     79379 non-null  float64
 18  females_allages_avg_vote   79379 non-null  float64
 19  Romance                    79379 non-null  int64
 20  Drama                      79379 non-null  int64
 21  Western                    79379 non-null  int64
 22  Comedy                     79379 non-null  int64
 23  Horror                     79379 non-null  int64
 24  Adventure                  79379 non-null  int64
 25  Mystery                    79379 non-null  int64
 26  Sci-Fi                     79379 non-null  int64
 27  Thriller                   79379 non-null  int64
 28  Crime                      79379 non-null  int64
 29  Musical                    79379 non-null  int64
 30  Fantasy                    79379 non-null  int64
 31  Biography                  79379 non-null  int64
 32  Action                     79379 non-null  int64
 33  War                        79379 non-null  int64
 34  Family                     79379 non-null  int64
 35  History                    79379 non-null  int64
 36  Music                      79379 non-null  int64
 37  Animation                  79379 non-null  int64
 38  Sport                      79379 non-null  int64
 39  Film-Noir                  79379 non-null  int64
 40  Documentary                79379 non-null  int64
 41  Reality-TV                 79379 non-null  int64
 42  News                       79379 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(27), object(8)
memory usage: 26.0+ MB

---

## Functions

### Pesquisa do filme (se ele existe na tabela)

In [8]:
df_movie_ratings[df_movie_ratings['original_title'].str.contains('Simpsons')]

,original_title,year,date_published,genre,duration,country,director,writer,production_company,actors,description,avg_vote,votes,weighted_average_vote,allgenders_18age_avg_vote,allgenders_30age_avg_vote,allgenders_45age_avg_vote,males_allages_avg_vote,females_allages_avg_vote,Romance,Drama,Western,Comedy,Horror,Adventure,Mystery,Sci-Fi,Thriller,Crime,Musical,Fantasy,Biography,Action,War,Family,History,Music,Animation,Sport,Film-Noir,Documentary,Reality-TV,News
44631,The Simpsons Movie,2007,2007-09-14,"Animation,Adventure,Comedy",87,USA,David Silverman,"James L. Brooks, Matt Groening",Twentieth Century Fox,"Dan Castellaneta, Julie Kavner, Nancy Cartwrig...","After Homer pollutes the town's water supply, ...",7.3,304958,7.3,7.4,7.3,7.1,7.3,7.2,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

---

In [9]:
def genreEquals(movie):
    genre_list_main = []
    genre_list = []
    movies_genres_equals = []
    
    index_movie = df_movie_ratings.loc[:, 'Romance':][df_movie_ratings['original_title'] == movie].index[0]
    
    
    select = pd.DataFrame(df_movie_ratings.loc[:, 'Romance':][df_movie_ratings['original_title'] == movie]
                                          .values[0]).T
    select.columns = [df_movie_ratings.loc[:, 'Romance':].columns]
    
    for i in range(0, len(select.columns[select.values[0] > 0])):
        genre_list_main.append(select.columns[select.values[0] > 0][i][0])
    genre_list_main.sort()
    
    
    for i in range(0, 1000):
        
        others_movies = pd.DataFrame(df_movie_ratings.loc[:, 'Romance':][df_movie_ratings.index != index_movie]
                                                     .values[i]).T
        others_movies.columns = [df_movie_ratings.loc[:, 'Romance':].columns]
        
        for i_columns in range(0, len(others_movies.columns[others_movies.values[0] > 0])):
            genre_list.append(others_movies.columns[others_movies.values[0] > 0][i_columns][0])
        genre_list.sort()
        
        
        if genre_list_main == genre_list:
            if int(df_movie_ratings[df_movie_ratings['original_title'] == movie].index[0]) < i:
                movies_genres_equals.append(df_movie_ratings['original_title'][i+1])
            else:
                movies_genres_equals.append(df_movie_ratings['original_title'][i])
        genre_list.clear()
                
    movies_genres_equals.sort()
            
    return movies_genres_equals

In [10]:
genreEquals("Cleopatra")

['Das Weib des Pharao',
 'Herr Arnes pengar',
 'In the Land of the Head Hunters',
 "Intolerance: Love's Struggle Throughout the Ages",
 'Nathan der Weise',
 'Novyy Vavilon',
 'Oktyabr',
 'Old Ironsides',
 'Quo Vadis?',
 'Romola',
 "Uncle Tom's Cabin"]

---

### Verificação

In [11]:
df_movie_ratings[df_movie_ratings['original_title'] == "Cleopatra"]

,original_title,year,date_published,genre,duration,country,director,writer,production_company,actors,description,avg_vote,votes,weighted_average_vote,allgenders_18age_avg_vote,allgenders_30age_avg_vote,allgenders_45age_avg_vote,males_allages_avg_vote,females_allages_avg_vote,Romance,Drama,Western,Comedy,Horror,Adventure,Mystery,Sci-Fi,Thriller,Crime,Musical,Fantasy,Biography,Action,War,Family,History,Music,Animation,Sport,Film-Noir,Documentary,Reality-TV,News
3,Cleopatra,1912,1912-11-13,"Drama,History",100,USA,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,5.2,5.3,5.0,5.3,5.1,5.9,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
88,Cleopatra,1917,1917-10-14,"Biography,Drama,History",125,USA,J. Gordon Edwards,"Adrian Johnson, Émile Moreau",Fox Film Corporation,"Theda Bara, Fritz Leiber, Thurston Hall, Alan ...","The story of Cleopatra, the fabulous queen of ...",6.5,298,6.5,6.3,6.4,6.9,6.4,7.1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0
1740,Cleopatra,1934,1934-10-05,"Biography,Drama,History",100,USA,Cecil B. DeMille,"Waldemar Young, Vincent Lawrence",Paramount Pictures,"Claudette Colbert, Warren William, Henry Wilco...",The man-hungry Queen of Egypt leads Julius Cae...,6.8,3331,6.8,6.8,6.7,6.9,6.8,6.9,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0
11036,Cleopatra,1963,1964-01-30,"Biography,Drama,History",192,"Switzerland, UK, USA",Joseph L. Mankiewicz,"Joseph L. Mankiewicz, Ranald MacDougall",Twentieth Century Fox,"Elizabeth Taylor, Richard Burton, Rex Harrison...",Queen Cleopatra VII of Egypt experiences both ...,7.0,28653,7.0,7.2,7.0,7.0,7.0,7.2,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0
40108,Cleopatra,2003,2003-08-14,"Comedy,Drama",104,"Spain, Argentina",Eduardo Mignogna,"Silvina Chague, Eduardo Mignogna",Televisión Federal (Telefe),"Norma Aleandro, Natalia Oreiro, Leonardo Sbara...",A retired teacher and a soap star leave their ...,6.7,574,6.7,6.6,6.7,6.6,6.6,7.4,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [12]:
df_movie_ratings[df_movie_ratings['original_title'] == "Romola"]

,original_title,year,date_published,genre,duration,country,director,writer,production_company,actors,description,avg_vote,votes,weighted_average_vote,allgenders_18age_avg_vote,allgenders_30age_avg_vote,allgenders_45age_avg_vote,males_allages_avg_vote,females_allages_avg_vote,Romance,Drama,Western,Comedy,Horror,Adventure,Mystery,Sci-Fi,Thriller,Crime,Musical,Fantasy,Biography,Action,War,Family,History,Music,Animation,Sport,Film-Noir,Documentary,Reality-TV,News
377,Romola,1924,1925-09-04,"Drama,History",102,USA,Henry King,"George Eliot, Will M. Ritchey",Inspiration Pictures,"Lillian Gish, Dorothy Gish, William Powell, Ro...","In Renaissance Florence, Tito, a no-good young...",6.3,164,6.3,6.5,6.4,5.9,6.1,7.1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

---

### Exemplo de como fica o DF na Função

In [13]:
pd.DataFrame(df_movie_ratings.loc[:, 'Romance':][df_movie_ratings['original_title'] != df_movie_ratings['original_title'][0]]
                                                     .values[0]).T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0

---

## Início para a tabela principal

### Semelhança entre o gênero dos outros filmes

In [14]:
StartIn = 0
NumberMovieSearch = 100


def genreEquality(moviegenre):
    genre_list_main = []
    genre_list = []
    movies_genres_equals = []
    
    index_movie = df_movie_ratings.loc[:, 'Romance':][df_movie_ratings['original_title'] == moviegenre].index[0]
    
    
    select = pd.DataFrame(df_movie_ratings.loc[:, 'Romance':][df_movie_ratings['original_title'] == moviegenre]
                                          .values[0]).T
    select.columns = [df_movie_ratings.loc[:, 'Romance':].columns]
    
    for i in range(0, len(select.columns[select.values[0] > 0])):
        genre_list_main.append(select.columns[select.values[0] > 0][i][0])
    
    
    for i in range(StartIn, NumberMovieSearch):
        
        others_movies = pd.DataFrame(df_movie_ratings.loc[:, 'Romance':][df_movie_ratings.index != index_movie]
                                                     .values[i]).T
        others_movies.columns = [df_movie_ratings.loc[:, 'Romance':].columns]
        other_movie = df_movie_ratings['original_title'][df_movie_ratings.index != index_movie].values[i]
        
        for i_columns in range(0, len(others_movies.columns[others_movies.values[0] > 0])):
            genre_list.append(others_movies.columns[others_movies.values[0] > 0][i_columns][0])
        
        equals_genres = list(filter(lambda x: x in genre_list_main, genre_list))
        
        if len(genre_list) > 1:
            percentage = len(equals_genres) / len(genre_list)
        else:
            percentage = len(equals_genres) / len(genre_list_main)
            
            
        movies_genres_equals.append([other_movie, percentage])
            
        genre_list.clear()
        equals_genres.clear()
        

    df_equals_genres = pd.DataFrame(movies_genres_equals, columns=['Movie', 'Equity Genre'])
    df_equals_genres['Equity Genre'] = df_equals_genres['Equity Genre'].round(2)
    
    
    return df_equals_genres

In [15]:
genreEquality("Cleopatra").sort_values(by='Equity Genre', ascending=False)

                                               Movie  Equity Genre
73  Intolerance: Love's Struggle Throughout the Ages          1.00
31                   In the Land of the Head Hunters          1.00
6                                         Quo Vadis?          1.00
53                              Martyrs of the Alamo          0.67
44                             The Birth of a Nation          0.67
..                                               ...           ...
69                                    The Half-Breed          0.00
67                                  The Good Bad-Man          0.00
65                                Flirting with Fate          0.00
58                                      Les vampires          0.00
0                                         Miss Jerry          0.00

[100 rows x 2 columns]

In [16]:
df_movie_ratings[df_movie_ratings['original_title'] == "Martyrs of the Alamo"]

,original_title,year,date_published,genre,duration,country,director,writer,production_company,actors,description,avg_vote,votes,weighted_average_vote,allgenders_18age_avg_vote,allgenders_30age_avg_vote,allgenders_45age_avg_vote,males_allages_avg_vote,females_allages_avg_vote,Romance,Drama,Western,Comedy,Horror,Adventure,Mystery,Sci-Fi,Thriller,Crime,Musical,Fantasy,Biography,Action,War,Family,History,Music,Animation,Sport,Film-Noir,Documentary,Reality-TV,News
54,Martyrs of the Alamo,1915,1915-11-21,"Drama,History,War",71,USA,Christy Cabanne,"Christy Cabanne, Theodosia Harris",Fine Arts Film Company,"Sam De Grasse, Allan Sears, Walter Long, Alfre...",The story of the defense of the mission-turned...,5.6,138,5.6,4.9,4.8,6.1,5.5,5.2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0

In [17]:
df_movie_ratings[df_movie_ratings['original_title'] == "Cleopatra"]

,original_title,year,date_published,genre,duration,country,director,writer,production_company,actors,description,avg_vote,votes,weighted_average_vote,allgenders_18age_avg_vote,allgenders_30age_avg_vote,allgenders_45age_avg_vote,males_allages_avg_vote,females_allages_avg_vote,Romance,Drama,Western,Comedy,Horror,Adventure,Mystery,Sci-Fi,Thriller,Crime,Musical,Fantasy,Biography,Action,War,Family,History,Music,Animation,Sport,Film-Noir,Documentary,Reality-TV,News
3,Cleopatra,1912,1912-11-13,"Drama,History",100,USA,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,5.2,5.3,5.0,5.3,5.1,5.9,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
88,Cleopatra,1917,1917-10-14,"Biography,Drama,History",125,USA,J. Gordon Edwards,"Adrian Johnson, Émile Moreau",Fox Film Corporation,"Theda Bara, Fritz Leiber, Thurston Hall, Alan ...","The story of Cleopatra, the fabulous queen of ...",6.5,298,6.5,6.3,6.4,6.9,6.4,7.1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0
1740,Cleopatra,1934,1934-10-05,"Biography,Drama,History",100,USA,Cecil B. DeMille,"Waldemar Young, Vincent Lawrence",Paramount Pictures,"Claudette Colbert, Warren William, Henry Wilco...",The man-hungry Queen of Egypt leads Julius Cae...,6.8,3331,6.8,6.8,6.7,6.9,6.8,6.9,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0
11036,Cleopatra,1963,1964-01-30,"Biography,Drama,History",192,"Switzerland, UK, USA",Joseph L. Mankiewicz,"Joseph L. Mankiewicz, Ranald MacDougall",Twentieth Century Fox,"Elizabeth Taylor, Richard Burton, Rex Harrison...",Queen Cleopatra VII of Egypt experiences both ...,7.0,28653,7.0,7.2,7.0,7.0,7.0,7.2,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0
40108,Cleopatra,2003,2003-08-14,"Comedy,Drama",104,"Spain, Argentina",Eduardo Mignogna,"Silvina Chague, Eduardo Mignogna",Televisión Federal (Telefe),"Norma Aleandro, Natalia Oreiro, Leonardo Sbara...",A retired teacher and a soap star leave their ...,6.7,574,6.7,6.6,6.7,6.6,6.6,7.4,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

---

### Semelhança dentre todos os aspectos

In [18]:
def generalEquality(movie, ordenation):
    columns = df_movie_ratings.columns[[5,6,7,8,9,0]]
    name_columns = ['Country', 'Director', 'Writer', 'Company', 'Actors', 'Title']
    movies_equals = []
    
    df_equals_movies = genreEquality(movie)
    
    for df in range(0, len(columns)):
        movie_list_main = []
        movie_list = []

        index_movie = df_movie_ratings.loc[:, f'{columns[df]}'][df_movie_ratings['original_title'] == movie].index[0]

        select = df_movie_ratings.loc[:, f'{columns[df]}'][df_movie_ratings['original_title'] == movie].values[0]
        movie_list_main.append(select.split(", "))


        for i in range(StartIn, NumberMovieSearch):

            others_movies = df_movie_ratings.loc[:, f'{columns[df]}'][df_movie_ratings.index != index_movie].values[i]
            movie_list.append(others_movies.split(", "))
            other_movie = df_movie_ratings['original_title'][df_movie_ratings.index != index_movie].values[i]

            equals_movies = list(filter(lambda x: x in movie_list_main[0], movie_list[0]))

            if len(movie_list[0]) > 1:
                percentage = len(equals_movies) / len(movie_list[0])
            else:
                percentage = len(equals_movies) / len(movie_list_main[0])

            movies_equals.append([other_movie, percentage])

            movie_list.clear()
            equals_movies.clear()
        
        df_equals_movies[['Movie', f'Equity {name_columns[df]}']] = pd.DataFrame(movies_equals)
        df_equals_movies[f'Equity {name_columns[df]}'] = df_equals_movies[f'Equity {name_columns[df]}'].round(2)
        movies_equals.clear()
        
    df_general_equality = df_equals_movies
    df_general_equality['General (%)'] = df_general_equality.loc[:, 'Equity Genre':].sum(axis=1)
    df_general_equality['General (%)'] = (df_general_equality['General (%)'] / 7).round(2) * 100
    
    try:
        return df_general_equality.sort_values(by=ordenation, ascending=False)
    except:
        return df_general_equality.sort_values(by='General (%)', ascending=False)

In [20]:
generalEquality('Juve contre Fantômas', '')

,Movie,Equity Genre,Equity Country,Equity Director,Equity Writer,Equity Company,Equity Actors,Equity Title,General (%)
25,Fantômas contre Fantômas,1.00,1.0,1.0,1.0,1.0,0.75,0.0,82.0
11,Fantômas - À l'ombre de la guillotine,1.00,1.0,1.0,1.0,1.0,0.50,0.0,79.0
15,Le mort qui tue,0.67,1.0,1.0,1.0,1.0,0.33,0.0,71.0
74,Judex,0.50,1.0,1.0,0.5,1.0,0.08,0.0,58.0
58,Les vampires,0.33,1.0,1.0,0.5,1.0,0.07,0.0,56.0
...,...,...,...,...,...,...,...,...,...
70,Hell's Hinges,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0
69,The Half-Breed,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0
67,The Good Bad-Man,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0
59,Young Romance,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0
0,Miss Jerry,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0